# Generated by Django 5.1.5 on 2025-01-30 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Observatie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("continut", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SesizareSector1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emiterii", models.DateTimeField(auto_now_add=True)),
                ("emitent", models.CharField(max_length=100)),
                ("comunicat_la", models.CharField(max_length=100)),
                ("punct_termic", models.CharField(max_length=30)),
                ("adresa", models.CharField(max_length=100)),
                ("acm_inc", models.CharField(max_length=5)),
                ("localizare", models.CharField(max_length=20)),
                ("distributie_transport", models.CharField(max_length=20)),
                ("scara_inchisa", models.BooleanField()),
                ("remediat", models.BooleanField()),
                ("data_remedierii", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dispecer1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cine_inchide_defectiunea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rezolvatSector1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observatii",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defectiuneSect1",
                        to="api.observatie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SesizareSector2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emiterii", models.DateTimeField(auto_now_add=True)),
                ("emitent", models.CharField(max_length=100)),
                ("comunicat_la", models.CharField(max_length=100)),
                ("punct_termic", models.CharField(max_length=30)),
                ("adresa", models.CharField(max_length=100)),
                ("acm_inc", models.CharField(max_length=5)),
                ("localizare", models.CharField(max_length=20)),
                ("distributie_transport", models.CharField(max_length=20)),
                ("scara_inchisa", models.BooleanField()),
                ("remediat", models.BooleanField()),
                ("data_remedierii", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dispecer2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cine_inchide_defectiunea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rezolvatSector2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observatii",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defectiuneSect2",
                        to="api.observatie",
                    ),
                ),
            ],
        ),
    ]
