# Generated by Django 5.1.5 on 2025-01-30 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sesizaresector2",
            name="author",
        ),
        migrations.RemoveField(
            model_name="sesizaresector2",
            name="cine_inchide_defectiunea",
        ),
        migrations.RemoveField(
            model_name="sesizaresector2",
            name="observatii",
        ),
        migrations.CreateModel(
            name="Sesizare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector", models.CharField(max_length=20)),
                ("data_emiterii", models.DateTimeField(auto_now_add=True)),
                ("emitent", models.CharField(max_length=100)),
                ("comunicat_la", models.CharField(max_length=100)),
                ("punct_termic", models.CharField(max_length=30)),
                ("adresa", models.CharField(max_length=100)),
                ("acm_inc", models.CharField(max_length=5)),
                ("localizare", models.CharField(max_length=20)),
                ("distributie_transport", models.CharField(max_length=20)),
                ("scara_inchisa", models.BooleanField()),
                ("remediat", models.BooleanField()),
                ("data_remedierii", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dispecer1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cine_inchide_defectiunea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rezolvatSector1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="observatie",
            name="sesizare",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sesizare",
                to="api.sesizare",
            ),
        ),
        migrations.DeleteModel(
            name="SesizareSector1",
        ),
        migrations.DeleteModel(
            name="SesizareSector2",
        ),
    ]
