# Generated by Django 5.1.5 on 2025-01-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_sesizaresector2_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sesizare",
            name="data_remedierii",
            field=models.DateTimeField(null=True),
        ),
    ]
