# Generated by Django 5.1.5 on 2025-02-03 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_sesizare_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sesizare",
            name="cine_inchide_defectiunea",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="rezolvatSector",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
